# Generated by Django 5.2.15 on 2026-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('resistencia', 'Resistencia'), ('capacitor', 'Capacitor'), ('led', 'LED'), ('transistor', 'Transistor'), ('diodo', 'Diodo'), ('inductor', 'Inductor'), ('sensor', 'Sensor'), ('display', 'Display'), ('modulo', 'Módulo'), ('conector', 'Conector'), ('cable', 'Cable'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('valor', models.CharField(blank=True, help_text='Ej: 10kΩ, 100µF, 5V', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(help_text='Ej: Caja roja, Bandeja 3', max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
