# Generated by Django 5.2.15 on 2026-06-15 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('microcontrolador', 'Microcontrolador'), ('placa', 'Placa de desarrollo'), ('modulo', 'Módulo'), ('otro', 'Otro')], default='placa', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Ej: Cajón 2, Caja azul', max_length=200)),
                ('directorio_pc', models.CharField(blank=True, help_text='Ruta en el PC', max_length=500)),
                ('repo_url', models.URLField(blank=True, verbose_name='Repositorio')),
                ('curso_finalizado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='placas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placa',
                'verbose_name_plural': 'Placas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='placas.placa')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
