# Generated by Django 5.2.15 on 2026-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placa',
            name='curso_finalizado',
        ),
        migrations.AddField(
            model_name='video',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
